const productTypes = {
    ADD_PRODUCT_START: "ADD_PRODUCT_START",
    FATCH_PRODUCTS_START: "FATCH_PRODUCTS_START",
    SET_PRODUCTS: "SET_PRODUCTS",
    FATCH_PRODUCT_START: "FATCH_PRODUCT_START",
    SET_PRODUCT: "SET_PRODUCT",
    DELETE_PRODUCT_START: "DELETE_PRODUCT_START",
    EDIT_PRODUCT_START: "EDIT_PRODUCT_START:"

};

export default productTypes;